[platformio]
default_envs = solakon_tracker_offline

[env:solakon_tracker_offline]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
board_build.flash_mode = dio
board_build.f_flash = 80000000L
board_build.flash_size = 4MB
board_build.partitions = partitions.csv
extra_scripts = pre:tools/embed_web_assets.py
monitor_speed = 115200
upload_speed = 460800
build_flags =
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MODE=1
  -D CORE_DEBUG_LEVEL=1
lib_deps =
  links2004/WebSockets @ ^2.6.1
  knolleary/PubSubClient @ ^2.8
  bblanchon/ArduinoJson @ ^6.21.5
