#!/usr/bin/env python3
"""Generate reproducible gzip-compressed browser assets for the firmware."""

import gzip
from pathlib import Path

Import("env")  # type: ignore[name-defined]  # Provided by PlatformIO/SCons.

ROOT = Path(env["PROJECT_DIR"])
GENERATED_DIR = Path(env.subst("$BUILD_DIR")) / "generated"
TARGET = GENERATED_DIR / "WebAssets.h"
ASSETS = (
    ("common.css", "kCommonCssGzip"),
    ("common.js", "kCommonJsGzip"),
    ("i18n.js", "kI18nJsGzip"),
    ("dashboard.js", "kDashboardJsGzip"),
    ("history.js", "kHistoryJsGzip"),
    ("maintenance.js", "kMaintenanceJsGzip"),
    ("setup.html", "kSetupHtmlGzip"),
    ("setup.js", "kSetupJsGzip"),
)


def format_bytes(data: bytes) -> str:
    rows = []
    for offset in range(0, len(data), 16):
        rows.append("  " + ", ".join(f"0x{byte:02x}" for byte in data[offset:offset + 16]))
    return ",\n".join(rows)


def build(*_args, **_kwargs) -> None:
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    declarations = []
    for filename, symbol in ASSETS:
        source = ROOT / "web" / filename
        raw = source.read_text(encoding="utf-8").replace("\r\n", "\n").encode("utf-8")
        compressed = gzip.compress(raw, compresslevel=9, mtime=0)
        declarations.append(
            f"static const uint8_t {symbol}[] PROGMEM = {{\n"
            + format_bytes(compressed)
            + "\n};\n"
            + f"static constexpr size_t {symbol}Size = {len(compressed)};\n"
        )
    header = (
        "#pragma once\n\n"
        "// Generated from web browser assets. Do not edit this file directly.\n"
        "#include <Arduino.h>\n\n"
        + "\n".join(declarations)
    )
    if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != header:
        TARGET.write_text(header, encoding="utf-8", newline="\n")


build()
env.Prepend(CPPPATH=[str(GENERATED_DIR)])
