#!/usr/bin/env python3
"""Generate reproducible gzip-compressed browser assets for the firmware."""

import gzip
import hashlib
import json
import re
from pathlib import Path

Import("env")  # type: ignore[name-defined]  # Provided by PlatformIO/SCons.

ROOT = Path(env["PROJECT_DIR"])
GENERATED_DIR = Path(env.subst("$BUILD_DIR")) / "generated"
TARGET = GENERATED_DIR / "WebAssets.h"
ASSET_FS_ROOT = GENERATED_DIR / "asset-partition"
ASSET_FS_DIR = ASSET_FS_ROOT / "assets"
ASSETS = (
    "common.css", "common.js", "i18n.js", "dashboard.js", "history.js",
    "maintenance.js", "diagnostics.js", "setup.html", "setup.js",
)
# All normal UI assets live in the existing read-only 64-kB container. The
# application binary intentionally retains only its compact recovery page.
PARTITION_ASSETS = set(ASSETS)


def minify_for_gzip(filename: str, text: str) -> str:
    """Conservative minification that never rewrites JS/CSS expressions."""
    lines = [
        line.strip()
        for line in text.replace("\r\n", "\n").split("\n")
        if line.strip()
    ]
    # diagnostics.js is authored as complete semicolon/braced statements per
    # line, therefore joining it cannot change automatic-semicolon behavior.
    separator = "" if filename == "diagnostics.js" else "\n"
    return separator.join(lines)


def build(*_args, **_kwargs) -> None:
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    ASSET_FS_DIR.mkdir(parents=True, exist_ok=True)
    main_source = (ROOT / "src" / "main.cpp").read_text(encoding="utf-8")
    version_match = re.search(
        r'kFirmwareVersion\[\]\s*=\s*"([^"]+)"', main_source
    )
    if not version_match:
        raise RuntimeError("kFirmwareVersion not found")
    firmware_version = version_match.group(1)
    manifest_files = {}
    report_files = {}
    for filename in ASSETS:
        source = ROOT / "web" / filename
        source_bytes = source.read_bytes()
        minified = minify_for_gzip(
            filename, source_bytes.decode("utf-8")
        ).encode("utf-8")
        compressed = gzip.compress(minified, compresslevel=9, mtime=0)
        asset_name = filename + ".gz"
        asset_path = ASSET_FS_DIR / asset_name
        if filename in PARTITION_ASSETS:
            if not asset_path.exists() or asset_path.read_bytes() != compressed:
                asset_path.write_bytes(compressed)
            manifest_files[asset_name] = {
                "size": len(compressed),
                "sha256": hashlib.sha256(compressed).hexdigest(),
            }
        elif asset_path.exists():
            asset_path.unlink()
        report_files[filename] = {
            "raw": len(source_bytes),
            "minified": len(minified),
            "gzip": len(compressed),
        }
    header = (
        "#pragma once\n\n"
        "// Generated asset metadata. Normal UI payloads are stored only in\n"
        "// the verified 64-kB asset container; do not edit this file.\n"
        "#include <stddef.h>\n\n"
        f"static constexpr size_t kExternalWebAssetCount = {len(ASSETS)};\n"
    )
    if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != header:
        TARGET.write_text(header, encoding="utf-8", newline="\n")
    manifest = {
        "schema": 1,
        "assets_version": firmware_version,
        "files": manifest_files,
    }
    manifest_text = json.dumps(
        manifest, ensure_ascii=False, separators=(",", ":"), sort_keys=True
    ) + "\n"
    manifest_path = ASSET_FS_DIR / "manifest.json"
    if not manifest_path.exists() or manifest_path.read_text(
        encoding="utf-8"
    ) != manifest_text:
        manifest_path.write_text(manifest_text, encoding="utf-8", newline="\n")
    report = {
        "assets_version": firmware_version,
        "files": report_files,
        "totals": {
            "raw": sum(item["raw"] for item in report_files.values()),
            "minified": sum(item["minified"] for item in report_files.values()),
            "gzip": sum(item["gzip"] for item in report_files.values()),
        },
    }
    report_path = GENERATED_DIR / "asset-build-report.json"
    report_text = json.dumps(report, ensure_ascii=False, indent=2) + "\n"
    if not report_path.exists() or report_path.read_text(
        encoding="utf-8"
    ) != report_text:
        report_path.write_text(report_text, encoding="utf-8", newline="\n")


build()
env.Prepend(CPPPATH=[str(GENERATED_DIR)])
env.Replace(PROJECT_DATA_DIR=str(ASSET_FS_ROOT))
