#!/usr/bin/env python3
"""Generate gzip-compressed browser assets for the ESP32 firmware image."""

import gzip
from pathlib import Path

Import("env")  # type: ignore[name-defined]  # Provided by PlatformIO/SCons.

ROOT = Path(env["PROJECT_DIR"])
SOURCE = ROOT / "web" / "i18n.js"
TARGET = ROOT / "src" / "WebAssets.h"


def format_bytes(data: bytes) -> str:
    rows = []
    for offset in range(0, len(data), 16):
        rows.append("  " + ", ".join(f"0x{byte:02x}" for byte in data[offset:offset + 16]))
    return ",\n".join(rows)


def build(*_args, **_kwargs) -> None:
    # Normalize line endings so Windows and Linux builds produce identical bytes.
    raw = SOURCE.read_text(encoding="utf-8").replace("\r\n", "\n").encode("utf-8")
    compressed = gzip.compress(raw, compresslevel=9, mtime=0)
    header = (
        "#pragma once\n\n"
        "// Generated from web/i18n.js. Do not edit this file directly.\n"
        "#include <Arduino.h>\n\n"
        "static const uint8_t kI18nJsGzip[] PROGMEM = {\n"
        + format_bytes(compressed)
        + "\n};\n"
        + f"static constexpr size_t kI18nJsGzipSize = {len(compressed)};\n"
    )
    if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != header:
        TARGET.write_text(header, encoding="utf-8", newline="\n")


build()
