const byId=id=>document.getElementById(id);let dashboardYearSummary=null;const fmt=(v,d,u)=>v==null?'–':Number(v).toLocaleString('de-DE',{minimumFractionDigits:d,maximumFractionDigits:d})+' '+u;const fmtPower=v=>v==null?'–':Math.abs(Number(v))>=1000?fmt(Number(v)/1000,2,'kW'):fmt(Number(v),1,'W');async function updateValues(){try{const response=await fetch('/api/v1/status',{cache:'no-store'});if(!response.ok)throw new Error('HTTP '+response.status);const s=await response.json();byId('powerValue').textContent=fmtPower(s.power_w);byId('importValue').textContent=fmt(s.import_kwh,3,'kWh');byId('exportValue').textContent=fmt(s.export_kwh,3,'kWh');byId('meterState').textContent=s.meter_fresh?'OK':'Warte';const has=s.phases&&s.phases.some(p=>p.power_w!=null||p.voltage_v!=null||p.current_a!=null);s.phases.forEach((p,i)=>{byId('phase'+i).innerHTML=[p.power_w==null?'':`<b>${fmtPower(p.power_w)}</b>`,p.voltage_v==null?'':fmt(p.voltage_v,1,'V'),p.current_a==null?'':fmt(p.current_a,2,'A')].filter(Boolean).join('<br>')||'<span class="muted">Vom Zähler nicht geliefert</span>'});}catch(error){byId('meterState').textContent='Offline';console.error(error)}}async function updateDashboardSummary(){try{const r=await fetch('/api/v1/dashboard-summary',{cache:'no-store'});if(!r.ok)throw Error(r.status);const s=await r.json();dashboardYearSummary=s;byId('todayImportSummary').textContent=fmt(s.today_import_kwh,3,'kWh');byId('todayExportSummary').textContent=fmt(s.today_export_kwh,3,'kWh');byId('yearImport').textContent=fmt(s.year_import_kwh,2,'kWh');byId('yearExport').textContent=fmt(s.year_export_kwh,2,'kWh');byId('yearDailyImport').textContent=fmt(s.year_daily_average_import_kwh,3,'kWh');byId('yearDailyExport').textContent=fmt(s.year_daily_average_export_kwh,3,'kWh');byId('yearCoverage').textContent=s.year_coverage_days==null?'Noch keine Jahresbasis verfügbar':'Jahreswerte seit Aufzeichnungsbeginn · Grundlage: '+Number(s.year_coverage_days).toLocaleString('de-DE',{maximumFractionDigits:1})+' Tage';const c=byId('dayComparison'),v=s.import_change_percent;c.textContent=v==null?'Keine Vergleichsdaten':(v>0?'+':'')+Number(v).toLocaleString('de-DE',{maximumFractionDigits:1})+' %';c.style.color=v==null?'':v>0?'#ff9b8f':v<0?'#63e68b':'';if(typeof periodStats==='function')periodStats();}catch(error){console.error(error)}}const refreshLive=()=>{if(!document.hidden)updateValues()};const refreshSummary=()=>{if(!document.hidden)updateDashboardSummary()};refreshLive();refreshSummary();setInterval(refreshLive,4000);setInterval(refreshSummary,60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden){refreshLive();refreshSummary();if(typeof dScheduleLoad==='function')dScheduleLoad(true,0)}});const pc=byId('powerChart'),px=pc.getContext('2d'),pw=byId('powerChartWrap');
let dd=[],dCursor=-1,dCursorPinned=false,dFrom=0,dTo=0,dExpectedStep=60,dAnchorState=new Date(),dVisible={power:true,import:true,export:true,gap:true};
const dCss=(name,fallback)=>getComputedStyle(document.documentElement).getPropertyValue(name).trim()||fallback;
const dColor={get power(){return dCss('--chart-power','#63e68b')},get import(){return dCss('--chart-import','#58a6ff')},get export(){return dCss('--chart-export','#ffb454')},get gap(){return dCss('--chart-gap','#ff4d4d')},get grid(){return dCss('--chart-grid','#355a43')},get label(){return dCss('--chart-label','#b8cdbf')}};
const dStep=()=>dExpectedStep;
const dPad=v=>String(v).padStart(2,'0');
function dIsoWeekValue(date){const x=new Date(Date.UTC(date.getFullYear(),date.getMonth(),date.getDate()));x.setUTCDate(x.getUTCDate()+4-(x.getUTCDay()||7));const year=x.getUTCFullYear(),first=new Date(Date.UTC(year,0,1)),week=Math.ceil((((x-first)/86400000)+1)/7);return `${year}-W${dPad(week)}`}
function dFromIsoWeek(value){const m=/^(\d{4})-W(\d{2})$/.exec(value);if(!m)return new Date(NaN);const jan4=new Date(Number(m[1]),0,4,12),monday=new Date(jan4);monday.setDate(jan4.getDate()-((jan4.getDay()+6)%7)+(Number(m[2])-1)*7);return monday}
const dConfig=()=>({hour:{max:168,type:'datetime-local',label:'Stunde',back:'Stunden'},day:{max:730,type:'date',label:'Kalendertag',back:'Tage'},week:{max:104,type:'week',label:'Kalenderwoche',back:'Wochen'},month:{max:60,type:'month',label:'Kalendermonat',back:'Monate'},year:{max:20,type:'number',label:'Kalenderjahr',back:'Jahre'}}[byId('dashRange').value]);
function dInputValue(date){const range=byId('dashRange').value,datePart=`${date.getFullYear()}-${dPad(date.getMonth()+1)}-${dPad(date.getDate())}`;if(range==='hour')return `${datePart}T${dPad(date.getHours())}:00`;if(range==='day')return datePart;if(range==='week')return dIsoWeekValue(date);if(range==='month')return datePart.slice(0,7);return String(date.getFullYear())}
function dReadInput(){const value=byId('dashDate').value,range=byId('dashRange').value;if(!value)return new Date(NaN);if(range==='hour')return new Date(value);if(range==='day')return new Date(value+'T12:00:00');if(range==='week')return dFromIsoWeek(value);if(range==='month')return new Date(value+'-15T12:00:00');return new Date(Number(value),6,1,12)}
const dAnchor=()=>new Date(dAnchorState);
function dRenderInput(){const input=byId('dashDate'),cfg=dConfig(),now=new Date();input.type=cfg.type;input.removeAttribute('min');input.removeAttribute('max');input.removeAttribute('step');if(cfg.type==='datetime-local'){input.step=3600;input.max=dInputValue(now)}else if(cfg.type==='date'||cfg.type==='week'||cfg.type==='month')input.max=dInputValue(now);else{input.min=String(now.getFullYear()-cfg.max);input.max=String(now.getFullYear());input.step=1}input.value=dInputValue(dAnchorState)}
function dShiftValue(date,amount){const range=byId('dashRange').value;if(range==='hour')date.setHours(date.getHours()+amount);else if(range==='day')date.setDate(date.getDate()+amount);else if(range==='week')date.setDate(date.getDate()+amount*7);else if(range==='month'){date.setDate(15);date.setMonth(date.getMonth()+amount)}else date.setFullYear(date.getFullYear()+amount);return date}
function dBackCount(value){const now=new Date(),range=byId('dashRange').value,ms=now-value,dayDiff=Math.floor((Date.UTC(now.getFullYear(),now.getMonth(),now.getDate())-Date.UTC(value.getFullYear(),value.getMonth(),value.getDate()))/86400000);if(range==='hour')return Math.max(0,Math.floor(ms/3600000));if(range==='day')return Math.max(0,dayDiff);if(range==='week')return Math.max(0,Math.floor(dayDiff/7));if(range==='month')return Math.max(0,(now.getFullYear()-value.getFullYear())*12+now.getMonth()-value.getMonth());return Math.max(0,now.getFullYear()-value.getFullYear())}
function dToggleDateNav(){const cfg=dConfig();byId('dashDateNav').hidden=!cfg;byId('dashAnchorLabel').textContent=cfg.label;byId('dashSliderLabel').textContent=`${cfg.back} zurückspulen`;byId('dashDaysBack').max=cfg.max;dRenderInput()}
function dSyncDate(load=true){let value=dReadInput(),now=new Date();if(!Number.isFinite(value.getTime())||value>now)value=now;dAnchorState=value;dRenderInput();const cfg=dConfig(),actual=dBackCount(value),back=Math.min(cfg.max,actual);byId('dashDaysBack').value=back;byId('dashDaysLabel').textContent=actual===0?'Aktueller Zeitraum':`${actual} ${cfg.back} zurück`;byId('dashNext').disabled=actual===0;if(load)dScheduleLoad()}
function dShiftDay(delta){dAnchorState=dShiftValue(dAnchor(),delta);dRenderInput();dSyncDate()}
function dFromSlider(back){dAnchorState=dShiftValue(new Date(),-back);dRenderInput();byId('dashDaysLabel').textContent=back===0?'Aktueller Zeitraum':`${back} ${dConfig().back} zurück`}
const dGapAfter=i=>irGapAfter(dd,i,dStep());
const dGapCount=()=>irGapCount(dd,dFrom,dTo,dStep());
const dPowerLabel=v=>Math.abs(v)>=1000?(v/1000).toLocaleString('de-DE',{maximumFractionDigits:1})+' kW':v.toLocaleString('de-DE',{maximumFractionDigits:1})+' W';
function dTimeAxis(ctx,left,right,width,y,from,to){const plot=width-left-right,visibleHours=Math.max(1,(to-from)/3600),vertical=plot/visibleHours<42,fullDay=byId('dashRange').value==='day',first=Math.ceil(from/900)*900;ctx.save();ctx.strokeStyle=dColor.label;ctx.fillStyle=dColor.label;for(let ts=first;ts<=to;ts+=900){const date=new Date(ts*1000),minute=date.getMinutes(),hour=minute===0,len=hour?12:minute===30?8:4,x=left+(ts-from)*plot/Math.max(1,to-from);ctx.globalAlpha=hour?1:minute===30?.7:.45;ctx.lineWidth=hour?1.6:1;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x,y+len);ctx.stroke();if(!hour)continue;const label=fullDay&&ts===to?'24:00':String(date.getHours()).padStart(2,'0')+':00';ctx.globalAlpha=1;ctx.font=(vertical?'10':'11')+'px system-ui';if(vertical){ctx.save();ctx.translate(x,y+16);ctx.rotate(-Math.PI/2);ctx.textAlign='right';ctx.textBaseline='middle';ctx.fillText(label,0,0);ctx.restore()}else{ctx.textBaseline='top';ctx.textAlign=ts===from?'left':ts===to?'right':'center';ctx.fillText(label,x,y+15)}}ctx.restore()}
function dDrawGaps(ctx,X,top,bottom){ctx.save();ctx.strokeStyle=dColor.gap;ctx.lineWidth=3;ctx.setLineDash([5,3]);const marker=x=>{ctx.beginPath();ctx.moveTo(x,top);ctx.lineTo(x,bottom);ctx.stroke()};dd.forEach((_,i)=>{if(dGapAfter(i))marker((X(i-1)+X(i))/2)});const edges=irGapEdges(dd,dFrom,dTo,dStep());if(edges.leading)marker(X(0));if(edges.trailing)marker(X(dd.length-1));ctx.restore()}
function dCursorLine(ctx,x,top,bottom){ctx.save();ctx.strokeStyle='#f7fff9';ctx.lineWidth=1.5;ctx.setLineDash([4,3]);ctx.beginPath();ctx.moveTo(x,top);ctx.lineTo(x,bottom);ctx.stroke();ctx.restore()}
function dPoint(ctx,x,y,color){if(!Number.isFinite(y))return;ctx.save();ctx.fillStyle=color;ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,5,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore()}
function dPlaceTip(tip,wrap,x){tip.style.display='block';const width=190;tip.style.left=Math.max(4,x>wrap.clientWidth/2?x-width-12:Math.min(wrap.clientWidth-width-4,x+12))+'px';tip.style.top='8px'}
function dHideTips(){byId('powerTip').style.display='none'}
function dYearComparison(value,baseline,compareId,baselineId,unit,reverse=false){const compare=byId(compareId),base=byId(baselineId),valid=Number.isFinite(value)&&Number.isFinite(baseline)&&baseline>0;base.textContent='Jahres-Ø'+(unit==='kWh'?' pro Tag':'')+': '+(Number.isFinite(baseline)?(unit==='W'?fmtPower(baseline):fmt(baseline,3,unit)):'–');if(!valid){compare.textContent='Kein Jahresvergleich';compare.style.color='';return}const percent=(value-baseline)/baseline*100;compare.textContent=(percent>0?'+':'')+percent.toLocaleString('de-DE',{maximumFractionDigits:1})+' % zum Jahres-Ø';const favorable=reverse?percent>0:percent<0;compare.style.color=Math.abs(percent)<.05?'':favorable?'#63e68b':'#ff9b8f'}
function pDraw(){
 if(!dd.length)return;const ratio=devicePixelRatio||1,w=pw.clientWidth,h=pw.clientHeight,L=w<480?62:64,R=12,T=14,timed=['hour','day'].includes(byId('dashRange').value),visibleHours=Math.max(1,(dTo-dFrom)/3600),B=timed&&((w-L-R)/visibleHours<42)?66:38;
 pc.width=Math.round(w*ratio);pc.height=Math.round(h*ratio);px.setTransform(ratio,0,0,ratio,0,0);px.clearRect(0,0,w,h);
 const power=dd.map(v=>v.avg),gridImport=power.map(v=>Number.isFinite(v)?Math.max(0,v):null),gridExport=power.map(v=>Number.isFinite(v)?Math.min(0,v):null),shown=[];if(dVisible.power)shown.push(...power);if(dVisible.import)shown.push(...gridImport);if(dVisible.export)shown.push(...gridExport);const values=shown.filter(Number.isFinite);if(!values.length)return;let lo=Math.min(0,...values),hi=Math.max(1,...values),pad=(hi-lo)*.08;hi+=pad;if(lo<0)lo-=pad;
 const X=i=>L+(dd[i].ts-dFrom)*(w-L-R)/Math.max(1,dTo-dFrom),Y=v=>T+(hi-v)*(h-T-B)/(hi-lo);px.font=(w<480?'11':'13')+'px system-ui';
 for(let i=0;i<5;i++){const v=hi-i*(hi-lo)/4,y=Y(v);px.strokeStyle=dColor.grid;px.lineWidth=1;px.beginPath();px.moveTo(L,y);px.lineTo(w-R,y);px.stroke();px.fillStyle=dColor.label;px.textAlign='right';px.textBaseline='middle';px.fillText(dPowerLabel(v),L-7,y)}
 if(lo<=0){px.strokeStyle='#d7e9dcaa';px.setLineDash([5,4]);px.beginPath();px.moveTo(L,Y(0));px.lineTo(w-R,Y(0));px.stroke();px.setLineDash([])}
 const ticks=w<480?3:5,span=dTo-dFrom;if(timed)dTimeAxis(px,L,R,w,h-B,dFrom,dTo);else{px.textAlign='center';px.textBaseline='top';for(let i=0;i<ticks;i++){const ts=dFrom+i*span/(ticks-1),d=new Date(ts*1000),x=L+i*(w-L-R)/(ticks-1),label=span>172800?d.toLocaleDateString('de-DE',{day:'2-digit',month:'2-digit'}):d.toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'});px.fillStyle=dColor.label;px.fillText(label,x,h-B+9)}}
 if(dVisible.gap)dDrawGaps(px,X,T,h-B);function line(vals,color){px.strokeStyle=color;px.lineWidth=2;px.lineJoin='round';px.lineCap='round';px.beginPath();let on=false;vals.forEach((v,i)=>{if(!Number.isFinite(v)||dGapAfter(i)){on=false;if(!Number.isFinite(v))return}on?px.lineTo(X(i),Y(v)):px.moveTo(X(i),Y(v));on=true});px.stroke()}if(dVisible.power)line(power,dColor.power);if(dVisible.import)line(gridImport,dColor.import);if(dVisible.export)line(gridExport,dColor.export);
 if(dCursor>=0&&dCursor<dd.length){const v=dd[dCursor],x=X(dCursor),parts=[];dCursorLine(px,x,T,h-B);if(Number.isFinite(v.avg)){if(dVisible.power){dPoint(px,x,Y(v.avg),dColor.power);parts.push(`Gesamtleistung: ${fmtPower(v.avg)}`)}if(v.avg>=0&&dVisible.import){dPoint(px,x,Y(v.avg),dColor.import);parts.push(`Netzbezug: ${fmtPower(v.avg)}`)}if(v.avg<0&&dVisible.export){dPoint(px,x,Y(v.avg),dColor.export);parts.push(`Einspeisung: ${fmtPower(-v.avg)}`)}}const tip=byId('powerTip');tip.innerHTML=`<strong>${new Date(v.ts*1000).toLocaleString('de-DE')}</strong><br>${parts.join('<br>')}<br>Minimum: ${fmtPower(v.min)}<br>Maximum: ${fmtPower(v.max)}`;dPlaceTip(tip,pw,x)}
}
function periodStats(){const valid=dd.filter(v=>Number.isFinite(v.avg)),energy=key=>{const values=dd.map(v=>v[key]).filter(Number.isFinite);return values.length>1?Math.max(0,values.at(-1)-values[0]):null},from=new Date(dFrom*1000),to=new Date((dTo-1)*1000),title=`${from.toLocaleString('de-DE',{dateStyle:'short',timeStyle:'short'})} – ${to.toLocaleString('de-DE',{dateStyle:'short',timeStyle:'short'})}`,average=valid.length?valid.reduce((s,x)=>s+x.avg,0)/valid.length:null,imported=energy('import'),exported=energy('export'),periodDays=Math.max(1/24,(dTo-dFrom)/86400),dailyImport=Number.isFinite(imported)?imported/periodDays:null,dailyExport=Number.isFinite(exported)?exported/periodDays:null;byId('averageLabel').textContent=`Ø Leistung · ${title}`;byId('periodImportLabel').textContent=`Netzbezug · ${title}`;byId('periodExportLabel').textContent=`Einspeisung · ${title}`;byId('morningAverage').textContent=Number.isFinite(average)?fmtPower(average):'Keine Daten';byId('periodImport').textContent=fmt(imported,3,'kWh');byId('periodExport').textContent=fmt(exported,3,'kWh');const y=dashboardYearSummary||{};dYearComparison(average,Number(y.year_average_power_w),'averageYearCompare','averageYearBaseline','W');dYearComparison(dailyImport,Number(y.year_daily_average_import_kwh),'importYearCompare','importYearBaseline','kWh');dYearComparison(dailyExport,Number(y.year_daily_average_export_kwh),'exportYearCompare','exportYearBaseline','kWh',true)}
let dLoadGeneration=0,dLoadController=null,dLoadTimer=0;
function dStopLoads(){++dLoadGeneration;clearTimeout(dLoadTimer);if(dLoadController)dLoadController.abort();dLoadController=null}
function dScheduleLoad(silent=false,delay=140){if(silent&&dLoadController)return;const generation=++dLoadGeneration;clearTimeout(dLoadTimer);if(dLoadController)dLoadController.abort();dLoadTimer=setTimeout(()=>dLoad(generation,silent),delay)}
async function dLoad(generation,silent=false){if(generation!==dLoadGeneration)return;dLoadController=new AbortController();const signal=dLoadController.signal;if(!silent){byId('dashLoading').hidden=false;byId('dashEmpty').hidden=true;pw.hidden=true}try{const range=byId('dashRange').value,anchor=Math.floor(dAnchor().getTime()/1000),url='/api/v1/history?range='+range+'&anchor='+anchor,r=await fetch(url,{cache:'no-store',signal});if(!r.ok)throw Error(r.status);const j=await r.json();if(generation!==dLoadGeneration)return;dd=j.values||[];dExpectedStep=Number(j.step)||60;dFrom=Number(j.from)||(dd.length?dd[0].ts:0);dTo=Number(j.to)||(dd.length?dd.at(-1).ts:dFrom+1);byId('dashLoading').hidden=true;periodStats();if(!dd.length){byId('dashEmpty').hidden=false;byId('dashSummary').textContent='Für diesen Zeitraum sind keine Messwerte gespeichert.';return}byId('dashEmpty').hidden=true;pw.hidden=false;byId('dashSummary').textContent=`${dd.length} Datenpunkte · ${dGapCount()} Datenlücken · ${new Date(dd[0].ts*1000).toLocaleString('de-DE')} bis ${new Date(dd.at(-1).ts*1000).toLocaleString('de-DE')}`;pDraw()}catch(e){if(e.name==='AbortError'||generation!==dLoadGeneration)return;if(!silent){byId('dashLoading').hidden=true;byId('dashEmpty').hidden=false;byId('dashEmpty').textContent='Diagramm konnte nicht geladen werden. Verbindung prüfen.'}}finally{if(generation===dLoadGeneration)dLoadController=null}}
function dMoveCursor(e,canvas){if(!dd.length)return;const r=canvas.getBoundingClientRect(),L=r.width<480?62:64,R=12,f=Math.max(0,Math.min(1,(e.clientX-r.left-L)/Math.max(1,r.width-L-R))),target=dFrom+f*(dTo-dFrom);dCursor=dd.reduce((best,v,i)=>Math.abs(v.ts-target)<Math.abs(dd[best].ts-target)?i:best,0);pDraw()}
function dBindCursor(canvas){let lastTap=0,lastTapX=0,tapTimer=0,touchActive=false;canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);touchActive=e.pointerType==='touch';if(touchActive||!dCursorPinned)dMoveCursor(e,canvas)});canvas.addEventListener('pointermove',e=>{if(e.pointerType==='touch'||!dCursorPinned)dMoveCursor(e,canvas)});canvas.addEventListener('pointerup',e=>{dMoveCursor(e,canvas);if(e.pointerType==='touch'){const now=Date.now(),doubleTap=now-lastTap<420&&Math.abs(e.clientX-lastTapX)<36;clearTimeout(tapTimer);if(doubleTap){dCursorPinned=true;lastTap=0}else{dCursorPinned=true;lastTap=now;lastTapX=e.clientX;tapTimer=setTimeout(()=>{dCursorPinned=false},430)}touchActive=false}});canvas.addEventListener('click',e=>{if(e.pointerType==='touch'||touchActive)return;if(e.detail===1){dCursorPinned=false;dMoveCursor(e,canvas)}});canvas.addEventListener('pointerleave',e=>{if(e.pointerType!=='touch'&&!dCursorPinned){dCursor=-1;dHideTips();pDraw()}});canvas.addEventListener('dblclick',e=>{if(e.pointerType==='touch')return;e.preventDefault();dMoveCursor(e,canvas);dCursorPinned=true})}
byId('dashDate').onchange=()=>dSyncDate();byId('dashPrev').onclick=()=>dShiftDay(-1);byId('dashToday').onclick=()=>{dAnchorState=new Date();dRenderInput();dSyncDate()};byId('dashNext').onclick=()=>dShiftDay(1);byId('dashDaysBack').oninput=e=>dFromSlider(Number(e.target.value));byId('dashDaysBack').onchange=()=>dSyncDate();dToggleDateNav();dSyncDate(false);
byId('dashRange').onchange=()=>{dCursor=-1;dCursorPinned=false;dHideTips();dToggleDateNav();dSyncDate(false);dScheduleLoad()};byId('powerLegend').querySelectorAll('[data-series]').forEach(button=>button.onclick=()=>{const series=button.dataset.series;dVisible[series]=!dVisible[series];button.setAttribute('aria-pressed',String(dVisible[series]));dHideTips();pDraw()});addEventListener('resize',pDraw);addEventListener('irtracker-theme-change',pDraw);dBindCursor(pc);addEventListener('keydown',e=>{if(e.key==='Escape'){dCursor=-1;dCursorPinned=false;dHideTips();pDraw()}});dScheduleLoad(false,0);
document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',dStopLoads,{capture:true}));addEventListener('pagehide',dStopLoads);
setInterval(()=>{if(!document.hidden)dScheduleLoad(true,0)},10000);
