const q=id=>document.getElementById(id),cv=q('chart'),cx=cv.getContext('2d'),wrap=q('chartWrap');
let raw=[],viewStart=0,viewEnd=1,hover=-1,drag=null,cursorPinned=false,compareData=[],rangeFrom=0,rangeTo=0,rangeStep=60,lastTouchTap=0,lastTouchX=0,touchTapTimer=0,touchActive=false,hAnchorState=new Date(),historyRequest=0,historyAbort=null,historyLoadTimer=0;
const hCss=(name,fallback)=>getComputedStyle(document.documentElement).getPropertyValue(name).trim()||fallback;
const colors={get avg(){return hCss('--chart-power','#63e68b')},min:'#69a7ff',max:'#ff8d69',get import(){return hCss('--chart-import','#58a6ff')},get export(){return hCss('--chart-export','#ffb454')},get gap(){return hCss('--chart-gap','#ff4d4d')},get grid(){return hCss('--chart-grid','#355a43')},get label(){return hCss('--chart-label','#b8cdbf')}};
const fmt=(v,d=2)=>v==null||!Number.isFinite(Number(v))?'–':Number(v).toLocaleString('de-DE',{minimumFractionDigits:d,maximumFractionDigits:d});
const fmtPower=v=>Math.abs(v)>=1000?fmt(v/1000,2)+' kW':fmt(v,1)+' W';
const expectedStep=()=>q('series').value==='power'&&q('metric').value==='minmax'&&rangeStep<60?60:rangeStep;
const hPad=v=>String(v).padStart(2,'0');
function hIsoWeekValue(date){const x=new Date(Date.UTC(date.getFullYear(),date.getMonth(),date.getDate()));x.setUTCDate(x.getUTCDate()+4-(x.getUTCDay()||7));const year=x.getUTCFullYear(),first=new Date(Date.UTC(year,0,1)),week=Math.ceil((((x-first)/86400000)+1)/7);return `${year}-W${hPad(week)}`}
function hFromIsoWeek(value){const m=/^(\d{4})-W(\d{2})$/.exec(value);if(!m)return new Date(NaN);const jan4=new Date(Number(m[1]),0,4,12),monday=new Date(jan4);monday.setDate(jan4.getDate()-((jan4.getDay()+6)%7)+(Number(m[2])-1)*7);return monday}
const hConfig=()=>({hour:{max:168,type:'datetime-local',label:'Stunde',back:'Stunden'},day:{max:730,type:'date',label:'Kalendertag',back:'Tage'},week:{max:104,type:'week',label:'Kalenderwoche',back:'Wochen'},month:{max:60,type:'month',label:'Kalendermonat',back:'Monate'},year:{max:20,type:'number',label:'Kalenderjahr',back:'Jahre'}}[q('range').value]);
function hInputValue(date){const range=q('range').value,datePart=`${date.getFullYear()}-${hPad(date.getMonth()+1)}-${hPad(date.getDate())}`;if(range==='hour')return `${datePart}T${hPad(date.getHours())}:00`;if(range==='day')return datePart;if(range==='week')return hIsoWeekValue(date);if(range==='month')return datePart.slice(0,7);return String(date.getFullYear())}
function hReadInput(){const value=q('historyDate').value,range=q('range').value;if(!value)return new Date(NaN);if(range==='hour')return new Date(value);if(range==='day')return new Date(value+'T12:00:00');if(range==='week')return hFromIsoWeek(value);if(range==='month')return new Date(value+'-15T12:00:00');return new Date(Number(value),6,1,12)}
const hAnchor=()=>new Date(hAnchorState);
function hRenderInput(){const input=q('historyDate'),cfg=hConfig(),now=new Date();input.type=cfg.type;input.removeAttribute('min');input.removeAttribute('max');input.removeAttribute('step');if(cfg.type==='datetime-local'){input.step=3600;input.max=hInputValue(now)}else if(cfg.type==='date'||cfg.type==='week'||cfg.type==='month')input.max=hInputValue(now);else{input.min=String(now.getFullYear()-cfg.max);input.max=String(now.getFullYear());input.step=1}input.value=hInputValue(hAnchorState)}
function hShiftValue(date,amount){const range=q('range').value;if(range==='hour')date.setHours(date.getHours()+amount);else if(range==='day')date.setDate(date.getDate()+amount);else if(range==='week')date.setDate(date.getDate()+amount*7);else if(range==='month'){date.setDate(15);date.setMonth(date.getMonth()+amount)}else date.setFullYear(date.getFullYear()+amount);return date}
function hBackCount(value){const now=new Date(),range=q('range').value,ms=now-value,dayDiff=Math.floor((Date.UTC(now.getFullYear(),now.getMonth(),now.getDate())-Date.UTC(value.getFullYear(),value.getMonth(),value.getDate()))/86400000);if(range==='hour')return Math.max(0,Math.floor(ms/3600000));if(range==='day')return Math.max(0,dayDiff);if(range==='week')return Math.max(0,Math.floor(dayDiff/7));if(range==='month')return Math.max(0,(now.getFullYear()-value.getFullYear())*12+now.getMonth()-value.getMonth());return Math.max(0,now.getFullYear()-value.getFullYear())}
function hToggleDateNav(){const cfg=hConfig();q('historyDateNav').hidden=!cfg;if(!cfg)return;q('historyAnchorLabel').textContent=cfg.label;q('historySliderLabel').textContent=`${cfg.back} zurückspulen`;q('historyDaysBack').max=cfg.max;hRenderInput()}
function hSyncDate(loadNow=true){let value=hReadInput(),now=new Date();if(!Number.isFinite(value.getTime())||value>now)value=now;hAnchorState=value;hRenderInput();const cfg=hConfig();if(cfg){const actual=hBackCount(value),back=Math.min(cfg.max,actual);q('historyDaysBack').value=back;q('historyDaysLabel').textContent=actual===0?'Aktueller Zeitraum':`${actual} ${cfg.back} zurück`;q('historyNext').disabled=actual===0}if(loadNow)scheduleLoad()}
function hShiftDay(delta){hAnchorState=hShiftValue(hAnchor(),delta);hRenderInput();hSyncDate()}
function hFromSlider(back){hAnchorState=hShiftValue(new Date(),-back);hRenderInput();q('historyDaysLabel').textContent=back===0?'Aktueller Zeitraum':`${back} ${hConfig().back} zurück`}
const gapAfter=(a,i)=>irGapAfter(a,i,expectedStep());
const gapCount=()=>irGapCount(raw,rangeFrom,rangeTo,expectedStep());
function setBusy(on){q('loading').hidden=!on;if(on){q('error').hidden=true;wrap.hidden=true}}
function fail(message,hint=''){setBusy(false);wrap.hidden=true;q('error').hidden=false;q('error').innerHTML='<strong>'+message+'</strong>'+(hint?'<br>'+hint:'')}
function energyDeltas(a,key){return a.map((v,i)=>({...v,value:i&&Number.isFinite(v[key])&&Number.isFinite(a[i-1][key])?Math.max(0,(v[key]-a[i-1][key])*1000):null}))}
function minutePower(a){if(rangeStep>=60)return a;const bins=[];for(const v of a){if(!Number.isFinite(v.avg))continue;const ts=Math.floor(v.ts/60)*60,last=bins.at(-1),minimum=Number.isFinite(v.min)?v.min:v.avg,maximum=Number.isFinite(v.max)?v.max:v.avg;if(!last||last.ts!==ts)bins.push({ts,avg:v.avg,min:minimum,max:maximum,sum:v.avg,count:1});else{last.sum+=v.avg;last.count++;last.avg=last.sum/last.count;last.min=Math.min(last.min,minimum);last.max=Math.max(last.max,maximum)}}return bins}
function active(){const s=q('series').value;if(s==='power')return q('metric').value==='minmax'?minutePower(raw):raw;if(s==='combined'){const i=energyDeltas(raw,'import'),e=energyDeltas(raw,'export');return i.map((v,n)=>({...v,importValue:v.value,exportValue:e[n].value}))}return energyDeltas(raw,s)}
function legend(){
 let h='';if(q('series').value==='power'){h+=item(colors.avg,'Durchschnitt');if(q('metric').value==='minmax')h+=item(colors.min,'Minimum')+item(colors.max,'Maximum')}
 else if(q('series').value==='combined')h=item(colors.import,'Netzbezug je Intervall')+item(colors.export,'Einspeisung je Intervall');
 else h=item(colors[q('series').value],q('series').value==='import'?'Netzbezug je Intervall':'Einspeisung je Intervall');
 h+=item(colors.gap,'Datenlücke / Ausfall');q('legend').innerHTML=h;q('modeBox').hidden=q('series').value!=='power'
}
function item(c,t){return `<span class='legend-item'><i class='swatch' style='background:${c}'></i>${t}</span>`}
function tickTime(ts,span){const d=new Date(ts*1000);return span>172800?d.toLocaleDateString('de-DE',{day:'2-digit',month:'2-digit',year:span>32000000?'2-digit':undefined}):d.toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})}
function hTimeAxis(ctx,left,right,width,y,from,to){const plot=width-left-right,visibleHours=Math.max(1,(to-from)/3600),vertical=plot/visibleHours<42,fullDay=q('range').value==='day',first=Math.ceil(from/900)*900;ctx.save();ctx.strokeStyle=colors.label;ctx.fillStyle=colors.label;for(let ts=first;ts<=to;ts+=900){const date=new Date(ts*1000),minute=date.getMinutes(),hour=minute===0,len=hour?12:minute===30?8:4,x=left+(ts-from)*plot/Math.max(1,to-from);ctx.globalAlpha=hour?1:minute===30?.7:.45;ctx.lineWidth=hour?1.6:1;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x,y+len);ctx.stroke();if(!hour)continue;const label=fullDay&&ts===rangeTo&&viewEnd===1?'24:00':String(date.getHours()).padStart(2,'0')+':00';ctx.globalAlpha=1;ctx.font=(vertical?'10':'11')+'px system-ui';if(vertical){ctx.save();ctx.translate(x,y+16);ctx.rotate(-Math.PI/2);ctx.textAlign='right';ctx.textBaseline='middle';ctx.fillText(label,0,0);ctx.restore()}else{ctx.textBaseline='top';ctx.textAlign=ts===from?'left':ts===to?'right':'center';ctx.fillText(label,x,y+15)}}ctx.restore()}
function visible(){const a=active(),n=a.length,s=Math.max(0,Math.min(n-1,Math.floor(viewStart*n))),e=Math.max(s+1,Math.min(n,Math.ceil(viewEnd*n)));return {a:a.slice(s,e),offset:s}}
function draw(){
 legend();const {a,offset}=visible();if(!a.length)return;
 const r=devicePixelRatio||1,w=wrap.clientWidth,h=wrap.clientHeight,L=w<480?62:64,R=12,T=16,timed=['hour','day'].includes(q('range').value),visibleHours=(rangeTo-rangeFrom)*(viewEnd-viewStart)/3600,B=timed&&((w-L-R)/Math.max(1,visibleHours)<42)?70:42;
 cv.width=Math.round(w*r);cv.height=Math.round(h*r);cx.setTransform(r,0,0,r,0,0);cx.clearRect(0,0,w,h);
 let vals=q('series').value==='power'?a.flatMap(x=>q('metric').value==='minmax'?[x.min,x.max]:[x.avg]):q('series').value==='combined'?a.flatMap(x=>[x.importValue,x.exportValue]):a.map(x=>x.value);
 vals=vals.filter(Number.isFinite);if(!vals.length)return fail('Für diesen Messwert sind noch keine Daten vorhanden.','Der Zähler muss Bezug bzw. Einspeisung als OBIS-Wert liefern.');
 let lo=q('series').value==='power'?Math.min(0,...vals):0,hi=Math.max(1,...vals);if(hi===lo)hi=lo+1;const pad=(hi-lo)*.08;hi+=pad;if(lo<0)lo-=pad;
 const domainStart=rangeFrom+(rangeTo-rangeFrom)*viewStart,domainEnd=rangeFrom+(rangeTo-rangeFrom)*viewEnd;
 const X=i=>L+(a[i].ts-domainStart)*(w-L-R)/Math.max(1,domainEnd-domainStart),Y=v=>T+(hi-v)*(h-T-B)/(hi-lo);
 cx.font=(w<480?'11':'13')+'px system-ui';cx.textBaseline='middle';
 for(let i=0;i<5;i++){const v=hi-i*(hi-lo)/4,y=Y(v);cx.strokeStyle=colors.grid;cx.lineWidth=1;cx.beginPath();cx.moveTo(L,y);cx.lineTo(w-R,y);cx.stroke();cx.fillStyle=colors.label;cx.textAlign='right';cx.fillText(fmt(v,Math.abs(v)<10?1:0)+(q('series').value==='power'?' W':' Wh'),L-7,y)}
 if(lo<=0&&hi>=0){const y=Y(0);cx.strokeStyle='#d7e9dc';cx.lineWidth=1.5;cx.setLineDash([5,4]);cx.beginPath();cx.moveTo(L,y);cx.lineTo(w-R,y);cx.stroke();cx.setLineDash([])}
 const ticks=w<480?3:5,span=domainEnd-domainStart;if(timed)hTimeAxis(cx,L,R,w,h-B,domainStart,domainEnd);else{cx.textAlign='center';cx.textBaseline='top';for(let i=0;i<ticks;i++){const ts=domainStart+i*span/(ticks-1),x=L+i*(w-L-R)/(ticks-1);cx.fillStyle=colors.label;cx.fillText(tickTime(ts,span),x,h-B+9)}}
 cx.save();cx.strokeStyle=colors.gap;cx.lineWidth=3;cx.setLineDash([5,3]);const gapMarker=x=>{cx.beginPath();cx.moveTo(x,T);cx.lineTo(x,h-B);cx.stroke()};a.forEach((_,i)=>{if(gapAfter(a,i))gapMarker((X(i-1)+X(i))/2)});const edges=irGapEdges(raw,rangeFrom,rangeTo,expectedStep()),firstTs=raw[0].ts,lastTs=raw.at(-1).ts;if(edges.leading&&firstTs>=domainStart&&firstTs<=domainEnd)gapMarker(L+(firstTs-domainStart)*(w-L-R)/Math.max(1,domainEnd-domainStart));if(edges.trailing&&lastTs>=domainStart&&lastTs<=domainEnd)gapMarker(L+(lastTs-domainStart)*(w-L-R)/Math.max(1,domainEnd-domainStart));cx.restore();
 function line(key,color,fill=false){cx.beginPath();let started=false;a.forEach((v,i)=>{const val=v[key];if(!Number.isFinite(val)||gapAfter(a,i)){started=false;if(!Number.isFinite(val))return}const x=X(i),y=Y(val);started?cx.lineTo(x,y):cx.moveTo(x,y);started=true});if(fill&&!gapCount()){cx.lineTo(X(a.length-1),Y(0));cx.lineTo(X(0),Y(0));cx.closePath();cx.fillStyle=color+'25';cx.fill()}cx.strokeStyle=color;cx.lineWidth=2;cx.lineJoin='round';cx.lineCap='round';cx.stroke()}
 if(q('series').value==='power'){if(q('metric').value==='minmax'){line('min',colors.min);line('max',colors.max)}line('avg',colors.avg)}
 else if(q('series').value==='combined'){line('importValue',colors.import,true);line('exportValue',colors.export,true)}
 else line('value',colors[q('series').value],true);
 if(hover>=offset&&hover<offset+a.length){const i=hover-offset,x=X(i),point=(v,color)=>{if(!Number.isFinite(v))return;cx.fillStyle=color;cx.strokeStyle='#fff';cx.lineWidth=2;cx.beginPath();cx.arc(x,Y(v),5,0,Math.PI*2);cx.fill();cx.stroke()};cx.save();cx.strokeStyle='#f7fff9';cx.lineWidth=1.5;cx.setLineDash([4,3]);cx.beginPath();cx.moveTo(x,T);cx.lineTo(x,h-B);cx.stroke();cx.restore();if(q('series').value==='power'){point(a[i].avg,colors.avg);if(q('metric').value==='minmax'){point(a[i].min,colors.min);point(a[i].max,colors.max)}}else if(q('series').value==='combined'){point(a[i].importValue,colors.import);point(a[i].exportValue,colors.export)}else point(a[i].value,colors[q('series').value])}
 q('summary').textContent=`${a.length} von ${raw.length} Datenpunkten · ${gapCount()} Datenlücken · ${new Date(a[0].ts*1000).toLocaleString('de-DE')} bis ${new Date(a.at(-1).ts*1000).toLocaleString('de-DE')}`;
}
function zoom(f,center=.5){const width=viewEnd-viewStart,nw=Math.max(.02,Math.min(1,width*f)),c=viewStart+width*center;viewStart=Math.max(0,Math.min(1-nw,c-nw*center));viewEnd=viewStart+nw;draw()}
function point(ev){const r=cv.getBoundingClientRect();return {x:ev.clientX-r.left,y:ev.clientY-r.top,w:r.width}}
function showTip(ev){if(!raw.length)return;const p=point(ev),{a,offset}=visible();if(!a.length)return;const L=p.w<480?62:64,R=12,f=Math.max(0,Math.min(1,(p.x-L)/Math.max(1,p.w-L-R))),from=rangeFrom+(rangeTo-rangeFrom)*viewStart,to=rangeFrom+(rangeTo-rangeFrom)*viewEnd,target=from+f*(to-from),i=a.reduce((best,v,n)=>Math.abs(v.ts-target)<Math.abs(a[best].ts-target)?n:best,0);hover=offset+i;const v=a[i],s=q('series').value;let text=`<strong>${new Date(v.ts*1000).toLocaleString('de-DE')}</strong><br>`;if(s==='power')text+=`Durchschnitt: ${fmtPower(v.avg)}<br>Minimum: ${fmtPower(v.min)}<br>Maximum: ${fmtPower(v.max)}`;else if(s==='combined')text+=`Netzbezug: ${fmt(v.importValue,3)} Wh<br>Einspeisung: ${fmt(v.exportValue,3)} Wh`;else text+=`${s==='import'?'Netzbezug':'Einspeisung'}: ${fmt(v.value,3)} Wh`;q('tooltip').innerHTML=text;q('tooltip').style.display='block';q('tooltip').style.left=Math.max(4,p.x>p.w/2?p.x-190:Math.min(p.w-190,p.x+12))+'px';q('tooltip').style.top='8px';draw()}
function historyPeriodStats(){const valid=raw.filter(v=>Number.isFinite(v.avg)),energy=key=>{const values=raw.map(v=>v[key]).filter(Number.isFinite);return values.length>1?Math.max(0,values.at(-1)-values[0]):null},from=new Date(rangeFrom*1000),to=new Date((rangeTo-1)*1000),title=`${from.toLocaleString('de-DE',{dateStyle:'short',timeStyle:'short'})} – ${to.toLocaleString('de-DE',{dateStyle:'short',timeStyle:'short'})}`;q('historyAverageLabel').textContent=`Ø Leistung · ${title}`;q('historyImportLabel').textContent=`Netzbezug · ${title}`;q('historyExportLabel').textContent=`Einspeisung · ${title}`;q('historyAverage').textContent=valid.length?fmtPower(valid.reduce((s,x)=>s+x.avg,0)/valid.length):'Keine Daten';q('todayImport').textContent=energy('import')==null?'Keine Daten':fmt(energy('import'),3)+' kWh';q('todayExport').textContent=energy('export')==null?'Keine Daten':fmt(energy('export'),3)+' kWh'}
async function getJson(url,signal){const r=await fetch(url,{cache:'no-store',signal});if(r.status===401)throw new Error('AUTH');if(!r.ok)throw new Error('HTTP '+r.status);return r.json()}
function stopHistoryLoads(){++historyRequest;clearTimeout(historyLoadTimer);if(historyAbort)historyAbort.abort();historyAbort=null}
function scheduleLoad(delay=140){const request=++historyRequest;clearTimeout(historyLoadTimer);if(historyAbort)historyAbort.abort();setBusy(true);historyLoadTimer=setTimeout(()=>load(request),delay)}
async function load(request){if(request!==historyRequest)return;historyAbort=new AbortController();const signal=historyAbort.signal,range=q('range').value,anchor=Math.floor(hAnchor().getTime()/1000),anchorPart=hConfig()?'&anchor='+anchor:'';viewStart=0;viewEnd=1;hover=-1;try{const d=await getJson('/api/v1/history?range='+range+anchorPart,signal);if(request!==historyRequest)return;raw=d.values||[];rangeStep=Number(d.step)||60;rangeFrom=Number(d.from)||(raw.length?raw[0].ts:0);rangeTo=Number(d.to)||(raw.length?raw.at(-1).ts:rangeFrom+1);historyPeriodStats();if(!raw.length)return fail('Für diesen Zeitraum sind keine Messwerte gespeichert.','Mit vorherigem Zeitraum, Zeitpunkt oder Schieberegler einen anderen Bereich auswählen.');setBusy(false);wrap.hidden=false;draw()}catch(e){if(e.name==='AbortError'||request!==historyRequest)return;fail(e.message==='AUTH'?'Anmeldung abgelaufen.':'Historie konnte nicht geladen werden.',e.message==='AUTH'?'Seite neu laden und erneut anmelden.':'WLAN-Verbindung prüfen und danach die Seite neu laden.')}finally{if(request===historyRequest)historyAbort=null}}
q('historyDate').onchange=()=>hSyncDate();q('historyPrev').onclick=()=>hShiftDay(-1);q('historyToday').onclick=()=>{hAnchorState=new Date();hRenderInput();hSyncDate()};q('historyNext').onclick=()=>hShiftDay(1);q('historyDaysBack').oninput=e=>hFromSlider(Number(e.target.value));q('historyDaysBack').onchange=()=>hSyncDate();hToggleDateNav();hSyncDate(false);
q('range').onchange=()=>{cursorPinned=false;hover=-1;q('tooltip').style.display='none';hToggleDateNav();hSyncDate(false);scheduleLoad()};q('series').onchange=draw;q('metric').onchange=draw;q('zoomIn').onclick=()=>zoom(.6);q('zoomOut').onclick=()=>zoom(1.7);q('reset').onclick=()=>{viewStart=0;viewEnd=1;draw()};
document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',stopHistoryLoads,{capture:true}));addEventListener('pagehide',stopHistoryLoads);
cv.addEventListener('wheel',e=>{e.preventDefault();const p=point(e);zoom(e.deltaY>0?1.25:.8,Math.max(0,Math.min(1,p.x/p.w)))},{passive:false});
cv.addEventListener('pointerdown',e=>{cv.setPointerCapture(e.pointerId);touchActive=e.pointerType==='touch';drag={mode:e.shiftKey?'pan':'cursor',x:e.clientX,start:viewStart,end:viewEnd};if(touchActive||!cursorPinned||e.shiftKey)showTip(e)});
cv.addEventListener('pointermove',e=>{if(drag&&drag.mode==='pan'){const width=drag.end-drag.start,dx=(e.clientX-drag.x)/cv.clientWidth*width;viewStart=Math.max(0,Math.min(1-width,drag.start-dx));viewEnd=viewStart+width;draw()}else if(e.pointerType==='touch'||!cursorPinned)showTip(e)});
cv.addEventListener('pointerup',e=>{drag=null;showTip(e);if(e.pointerType==='touch'){const now=Date.now(),doubleTap=now-lastTouchTap<420&&Math.abs(e.clientX-lastTouchX)<36;clearTimeout(touchTapTimer);if(doubleTap){cursorPinned=true;lastTouchTap=0}else{cursorPinned=true;lastTouchTap=now;lastTouchX=e.clientX;touchTapTimer=setTimeout(()=>{cursorPinned=false},430)}touchActive=false}});cv.addEventListener('click',e=>{if(e.pointerType==='touch'||touchActive)return;if(e.detail===1){cursorPinned=false;showTip(e)}});cv.addEventListener('pointerleave',e=>{if(e.pointerType!=='touch'&&!drag&&!cursorPinned){q('tooltip').style.display='none';hover=-1;draw()}});cv.addEventListener('dblclick',e=>{if(e.pointerType==='touch')return;e.preventDefault();showTip(e);cursorPinned=true});addEventListener('keydown',e=>{if(e.key==='Escape'){cursorPinned=false;hover=-1;q('tooltip').style.display='none';draw()}});
addEventListener('resize',draw);addEventListener('irtracker-theme-change',draw);
fetch('/api/v1/time',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'epoch='+Math.floor(Date.now()/1000)}).finally(()=>scheduleLoad(0));
