(function(){
const storageKey='irtracker-language-v1';
const originalTitle=document.title;
const requestedLanguage=new URLSearchParams(location.search).get('lang');
if(requestedLanguage==='de'||requestedLanguage==='en'){try{localStorage.setItem(storageKey,requestedLanguage)}catch(e){}}
const translations={
"Sprache wechseln":"Change language","Farben":"Colors","Farbschema anpassen":"Customize color scheme","Farbschema":"Color scheme","Schließen":"Close","Farben werden sofort und ausschließlich in diesem Browser gespeichert.":"Colors are applied immediately and stored only in this browser.","Hintergrund":"Background","Karten":"Cards","Standardfarben wiederherstellen":"Restore default colors",
"Dashboard":"Dashboard","Einstellungen":"Settings","Historie":"History","Schnittstellen":"Interfaces","Wartung":"Maintenance","Diagnose":"Diagnostics",
"Aktuelle Leistung":"Current power","Netzbezug":"Grid import","Einspeisung":"Grid export","Zählerstatus":"Meter status","Phasenwerte live":"Live phase values","Es werden ausschließlich tatsächlich vom Zähler übertragene Werte angezeigt.":"Only values actually transmitted by the meter are shown.","Vom Zähler nicht geliefert":"Not supplied by the meter","Energieübersicht":"Energy overview","Tag, Vergleich und laufendes Kalenderjahr":"Day, comparison and current calendar year","Netzbezug heute":"Grid import today","Einspeisung heute":"Grid export today","Bezug zu gestern, gleiche Uhrzeit":"Import versus yesterday at the same time","Netzbezug im Jahr":"Grid import this year","Einspeisung im Jahr":"Grid export this year","Ø Netzbezug pro Tag im Jahr":"Average daily grid import this year","Ø Einspeisung pro Tag im Jahr":"Average daily grid export this year","Jahreswerte werden aus der verfügbaren lokalen Historie berechnet.":"Annual values are calculated from the available local history.","Verlauf":"Charts","Verbrauch und Einspeisung direkt auf dem Tracker":"Consumption and export directly on the tracker","Erweiterte Auswertung öffnen":"Open advanced analysis","Zeitraum":"Period","1 Stunde":"1 hour","Kalendertag (00:00–24:00)":"Calendar day (00:00–24:00)","Kalenderwoche (Mo–So)":"Calendar week (Mon–Sun)","Kalendermonat":"Calendar month","Kalenderjahr":"Calendar year","Zeitpunkt":"Point in time","Vorheriger Zeitraum":"Previous period","Aktueller Zeitraum":"Current period","Nächster Zeitraum":"Next period","Schnell zurückspulen":"Quick rewind","Aktuell":"Current","Ø Leistung im Zeitraum":"Average power in period","Netzbezug im Zeitraum":"Grid import in period","Einspeisung im Zeitraum":"Grid export in period","Diagramm wird geladen …":"Loading chart…","Noch keine historischen Werte vorhanden.":"No historical readings available yet.","Leistung":"Power","Gesamtleistung":"Total power","Datenlücke / Ausfall":"Data gap / outage","Netzbezug und Einspeisung":"Grid import and export","Lokal · ohne Cloud":"Local · no cloud",
"Lokale Historie":"Local history","Messwert":"Metric","Leistungsanzeige":"Power display","Durchschnitt":"Average","Durchschnitt mit Min/Max":"Average with min/max","Minimum":"Minimum","Maximum":"Maximum","Zoom +":"Zoom +","Zoom –":"Zoom –","Gesamt":"All","Kalendertag":"Calendar day","Stunde":"Hour","Tage zurückspulen":"Rewind days","Stunden zurückspulen":"Rewind hours","Langzeit":"Long term","Bezug und Einspeisung":"Import and export","CSV exportieren":"Export CSV","Vollständige Historie als CSV exportieren":"Export complete history as CSV",
"Nur lesende Messwertausgabe":"Read-only meter output","Der Tracker sendet keine Sollwerte":"The tracker does not send setpoints","Null-Einspeisung, Ladegrenzen und Zeitpläne werden ausschließlich im Speicher oder Wechselrichter eingestellt. Der IR-Tracker stellt dafür nur die gemessene Netzleistung bereit.":"Zero export, charge limits and schedules are configured exclusively in the battery or inverter. The IR tracker only provides the measured grid power.","Shelly-kompatibel":"Shelly compatible","Für Speicher, die einen Shelly EM oder Shelly Pro EM als externen Zähler unterstützen.":"For batteries that support a Shelly EM or Shelly Pro EM as an external meter.","Home Assistant / MQTT":"Home Assistant / MQTT","MQTT und automatische Home-Assistant-Erkennung werden unter Einstellungen konfiguriert.":"MQTT and automatic Home Assistant discovery are configured under Settings.","MQTT konfigurieren":"Configure MQTT","Universelle aktuelle Messwerte für ioBroker, Node-RED, openHAB und eigene Systeme.":"Universal current readings for ioBroker, Node-RED, openHAB and custom systems.","Monitoring und Export":"Monitoring and export","Sicherheitsprinzip":"Security principle","Alle hier aufgeführten Schnittstellen geben Messwerte aus. Es werden keine Register am Speicher beschrieben und keine Lade- oder Entladebefehle verschickt.":"All interfaces listed here provide readings only. No battery registers are written and no charge or discharge commands are sent.",
"Backup und Wartung":"Backup and maintenance","Enthält WLAN-, MQTT-, PIN- und Geräteprofil-Daten. Die Datei enthält Geheimnisse und muss sicher aufbewahrt werden.":"Contains Wi-Fi, MQTT, PIN and device profile data. The file contains secrets and must be stored securely.","Vollständiges Backup erstellen":"Create complete backup","Nur Einstellungen herunterladen":"Download settings only","Backup wiederherstellen":"Restore backup","Einstellungen prüfen und wiederherstellen":"Validate and restore settings","Alle vier Ringpuffer werden als eine JSON-Datei im Browser zusammengeführt.":"All four ring buffers are combined into one JSON file in the browser.","Historie herunterladen":"Download history","Historienbackup":"History backup","Historie gestaffelt wiederherstellen":"Restore tiered history","Gesamte Historie löschen":"Delete all history","Custom-Firmware aktualisieren":"Update custom firmware","Es werden ausschließlich kryptografisch signierte IRFW-Pakete von Michael Roßmann akzeptiert. Signatur und ESP32-Image werden vor der Aktivierung geprüft.":"Only cryptographically signed IRFW packages from Michael Roßmann are accepted. The signature and ESP32 image are verified before activation.","Signiertes Firmwarepaket (.irfw)":"Signed firmware package (.irfw)","WLAN-Update installieren":"Install Wi-Fi update","Tracker sicher ausschalten":"Safely shut down tracker","Speichert den offenen Minutenblock und versetzt den ESP32 danach in Tiefschlaf. Zum Wiedereinschalten Strom kurz aus- und einschalten oder Reset betätigen.":"Saves the open minute block and then puts the ESP32 into deep sleep. To switch it back on, briefly cycle power or press reset.","Sicher herunterfahren":"Shut down safely","Ereignis- und Fehlerprotokoll":"Event and error log","Protokoll laden":"Load log","Protokoll löschen":"Clear log",
"WLAN-Verbindungen":"Wi-Fi connections","Bis zu drei Netze. Der Tracker probiert sie der Reihe nach. Ist keines erreichbar, startet automatisch der Setup-Hotspot.":"Up to three networks. The tracker tries them in order. If none is reachable, the setup hotspot starts automatically.","Netzwerkname":"Network name","Passwort":"Password","gespeichert":"stored","offenes WLAN":"open Wi-Fi","Hostname":"Host name","Zeitzone (POSIX-TZ)":"Time zone (POSIX TZ)","Setup-Hotspot Laufzeit (Minuten)":"Setup hotspot duration (minutes)","Neues Admin-Passwort":"New admin password","unverändert lassen":"leave unchanged","Neues Admin-Passwort wiederholen":"Repeat new admin password","Stromzähler":"Electricity meter","IR-Eingang (GPIO)":"IR input (GPIO)","IR-Sendeausgang (GPIO, -1 = aus)":"IR transmit output (GPIO, -1 = off)","Aus":"Off","IR-Sniffer auf Port 81 aktivieren":"Enable IR sniffer on port 81","Schreibende IR-Bridge aktivieren":"Enable writable IR bridge","Aus Sicherheitsgründen standardmäßig deaktiviert.":"Disabled by default for security.","Status-LED (GPIO, -1 = aus)":"Status LED (GPIO, -1 = off)","LED invertieren":"Invert LED","Baudrate":"Baud rate","Zugriffsmodus":"Access mode","Lokal offen (Integrationen ohne Anmeldung)":"Open locally (integrations without login)","Admin-Anmeldung erforderlich":"Admin login required","API und Shelly-Kompatibilität deaktiviert":"API and Shelly compatibility disabled","Ereignis- und Fehlerprotokoll dauerhaft im Flash speichern":"Persist event and error log in flash","MQTT-Server":"MQTT server","Benutzer":"User","optional":"optional","Home-Assistant-Discovery aktivieren":"Enable Home Assistant discovery","Energiesparen":"Energy saving","Eco-Modus aktivieren":"Enable Eco mode","Status-LED bei fehlerfreiem Eco-Betrieb ausschalten":"Turn status LED off during error-free Eco operation","WLAN-Sendeleistung im Eco-Modus automatisch anpassen":"Automatically adjust Wi-Fi transmit power in Eco mode","Alle Einstellungen speichern":"Save all settings","Diesen Browser abmelden":"Log out this browser",
"Backup & System":"Backup & system","Diagnose & Zähler":"Diagnostics & meter","Wartung – Diagnose":"Maintenance – diagnostics","Geführter Selbsttest":"Guided self-test","Selbsttest ausführen":"Run self-test","Zählerbericht":"Meter report","Detailliert anzeigen: empfangene und fehlende OBIS-Werte":"Show details: received and missing OBIS values","Technische Details":"Technical details","Speicherinformationen":"Memory information","Alle erkannten OBIS-Werte":"All detected OBIS values","Letztes SML-Telegramm (Hex)":"Latest SML telegram (hex)","Die Bridge ist nur aktiv, wenn ein TX-GPIO eingestellt wurde.":"The bridge is active only when a TX GPIO is configured.","Optionale IR-Freischaltung (experimentell)":"Optional IR unlock (experimental)","Zähler mit gespeicherter PIN freischalten":"Unlock meter with stored PIN","Stromzähler-PIN über IR":"Electricity meter PIN via IR","Vierstellige PIN":"Four-digit PIN","PIN lokal speichern":"Store PIN locally","PIN-Impulsfolge starten":"Start PIN pulse sequence","Gespeicherte PIN und Automatik löschen":"Delete stored PIN and automation","Einzelnen Testimpuls senden":"Send single test pulse","IR-Sendung stoppen":"Stop IR transmission","JSON-API für Experten":"JSON API for experts",
"Spannung und Strom werden nur live im RAM gehalten, niemals in der Flash-Historie.":"Voltage and current are kept live in RAM only and are never stored in flash history.","Nur für Zähler, die diese optische Impulsfolge unterstützen. Sendet automatisch Initialisierung, gespeicherte PIN, Navigation zu Inf und den langen Impuls für Inf ON. Danach prüft der Tracker bis zu 90 Sekunden auf Momentanleistung.":"Only for meters that support this optical pulse sequence. It sends initialization, the stored PIN, navigation to Inf and the long pulse for Inf ON. The tracker then checks for instantaneous power for up to 90 seconds.","Unterstützt der Zähler keine optische PIN-Steuerung, erfolgt die Freischaltung mit Zählertaste oder Taschenlampe.":"If the meter does not support optical PIN control, unlock it using the meter button or a flashlight.","Für Home Assistant, ioBroker, Node-RED, openHAB und eigene lokale Auswertungen. Die API ist keine eigene Bedienseite und bleibt deshalb aus der Hauptnavigation ausgeblendet.":"For Home Assistant, ioBroker, Node-RED, openHAB and custom local analysis. The API is not a user interface and is therefore hidden from the main navigation.",
"Firmware von Michael Roßmann · © 2026 Michael Roßmann · PolyForm Noncommercial 1.0.0 · nur nichtkommerzielle Nutzung":"Firmware by Michael Roßmann · © 2026 Michael Roßmann · PolyForm Noncommercial 1.0.0 · noncommercial use only","Unabhängiges Community-Projekt; nicht mit Solakon verbunden und nicht von Solakon unterstützt.":"Independent community project; not affiliated with or endorsed by Solakon."
};
const originals=new WeakMap();
const attrOriginals=new WeakMap();
function language(){try{return localStorage.getItem(storageKey)==='en'?'en':'de'}catch(e){return 'de'}}
function translated(value,lang){const clean=value.trim();return lang==='en'&&translations[clean]?value.replace(clean,translations[clean]):value}
function applyLanguage(){const lang=language();document.documentElement.lang=lang;document.title=lang==='en'&&translations[originalTitle]?translations[originalTitle]:originalTitle;const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let node;while(node=walker.nextNode()){if(!node.parentElement||['SCRIPT','STYLE'].includes(node.parentElement.tagName))continue;if(!originals.has(node))originals.set(node,node.nodeValue);const original=originals.get(node);node.nodeValue=translated(original,lang)}document.querySelectorAll('[placeholder],[aria-label],[title]').forEach(el=>{if(!attrOriginals.has(el)){const saved={};['placeholder','aria-label','title'].forEach(a=>{if(el.hasAttribute(a))saved[a]=el.getAttribute(a)});attrOriginals.set(el,saved)}Object.entries(attrOriginals.get(el)).forEach(([a,v])=>el.setAttribute(a,translated(v,lang)))});const button=document.getElementById('langToggle');if(button)button.textContent=lang==='de'?'English':'Deutsch';window.dispatchEvent(new CustomEvent('irtracker-language-change',{detail:{language:lang}}))}
const observer=new MutationObserver(()=>{observer.disconnect();applyLanguage();observer.observe(document.body,{childList:true,subtree:true})});
document.getElementById('langToggle').addEventListener('click',()=>{try{localStorage.setItem(storageKey,language()==='de'?'en':'de')}catch(e){}applyLanguage()});
applyLanguage();observer.observe(document.body,{childList:true,subtree:true});window.irTrackerLanguage=language;window.irTrackerTranslate=(de,en)=>language()==='en'?en:de;
})();
