(()=>{
const el=id=>document.getElementById(id),status=text=>{el('maintenanceStatus').textContent=text};
const updateText=error=>{if(error==='network_not_connected')return'Keine LAN- oder WLAN-Verbindung. Netzwerkverbindung prüfen.';if(error==='system_time_not_synchronized')return'Die Gerätezeit ist noch nicht synchronisiert.';if(error==='github_json_invalid')return'Die Antwort der Updatequelle konnte nicht verarbeitet werden.';if(error.startsWith('github_http_'))return'Die Updatequelle ist momentan nicht erreichbar.';return'Die Updateprüfung konnte nicht abgeschlossen werden.'};
async function loadUpdate(){try{const response=await fetch('/api/v1/update/status'),update=await response.json();el('updateCurrent').textContent=update.current_version;el('updateAvailable').textContent=update.available?update.latest_version:'–';el('updateLast').textContent=update.last_success?new Date(update.last_success*1000).toLocaleString():'Noch nicht geprüft';el('updateInstall').hidden=!update.available;const state=el('updateState'),details=el('updateError');details.hidden=!update.error;el('updateErrorCode').textContent=update.error||'';state.className=update.error?'error':update.checked?'status-pill':'muted';state.textContent=update.error?'Updateprüfung fehlgeschlagen: '+updateText(update.error):update.available?'Eine neuere signierte Firmware ist verfügbar.':update.checked?'Die installierte Firmware ist aktuell.':'Es wurde in dieser Laufzeit noch keine manuelle Prüfung durchgeführt.'}catch(_){el('updateState').className='error';el('updateState').textContent='Update-Status konnte nicht geladen werden.'}}
const download=(name,data)=>{const anchor=document.createElement('a');anchor.href=URL.createObjectURL(new Blob([data],{type:'application/json'}));anchor.download=name;anchor.click();setTimeout(()=>URL.revokeObjectURL(anchor.href),1000)};
el('fullBackup').onclick=()=>{status('Vollständiges Backup wird erstellt …');el('settingsExport').click();setTimeout(()=>el('historyExport').click(),800)};
el('settingsExport').onclick=async()=>{status('Einstellungen werden geladen …');const response=await fetch('/api/v1/backup/settings');download('irtracker-settings.json',await response.text());status('Einstellungsbackup erstellt')};
el('settingsImport').onclick=async()=>{const file=el('settingsFile').files[0];if(!file)return status('Bitte Einstellungsbackup auswählen');const text=await file.text();let data;try{data=JSON.parse(text)}catch(_){return status('Ungültige JSON-Datei')}if(data.format!=='irtracker-settings'||data.version!==1)return status('Falsches Backupformat');if(!confirm('Einstellungen ersetzen und Tracker neu starten?'))return;const response=await fetch('/api/v1/backup/settings/restore',{method:'POST',headers:{'Content-Type':'application/json'},body:text});status(response.ok?'Wiederhergestellt, Tracker startet neu':'Wiederherstellung fehlgeschlagen')};
el('historyExport').onclick=async()=>{status('Historie wird gestreamt …');const out={format:'irtracker-history',version:1,created:new Date().toISOString(),tiers:{}};for(const[name,range]of Object.entries({minute:'minute_all',quarter:'quarter_all',hour:'hour_all',day:'day_all'})){const response=await fetch('/api/v1/history?range='+range);if(!response.ok)return status('Fehler bei '+name);out.tiers[name]=(await response.json()).values}download('irtracker-history.json',JSON.stringify(out));status('Historienbackup erstellt')};
el('historyImport').onclick=async()=>{const file=el('historyFile').files[0];if(!file)return status('Bitte Historienbackup auswählen');let backup;try{backup=JSON.parse(await file.text())}catch(_){return status('Ungültige JSON-Datei')}if(backup.format!=='irtracker-history'||backup.version!==1||!backup.tiers)return status('Falsches Backupformat');for(const name of['minute','quarter','hour','day']){if(!Array.isArray(backup.tiers[name]))return status('Historienstufe fehlt: '+name);if(!backup.tiers[name].every(value=>Number.isInteger(value.ts)&&value.ts>=1700000000&&Number.isFinite(value.avg)&&Number.isFinite(value.min)&&Number.isFinite(value.max)&&(value.import==null||Number.isFinite(value.import))&&(value.export==null||Number.isFinite(value.export))))return status('Ungültiger Datensatz in '+name)}if(!confirm('Vorhandene Historie durch dieses Backup ersetzen?'))return;for(const name of['minute','quarter','hour','day']){status('Importiere '+name+' …');let response=await fetch('/api/v1/history/import/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tier:name})});if(!response.ok)return status('Start fehlgeschlagen: '+name);for(let offset=0;offset<backup.tiers[name].length;offset+=50){response=await fetch('/api/v1/history/import/batch',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tier:name,values:backup.tiers[name].slice(offset,offset+50)})});if(!response.ok)return status('Import fehlgeschlagen: '+name+' '+offset);status('Importiere '+name+': '+Math.min(offset+50,backup.tiers[name].length)+' / '+backup.tiers[name].length)}}status('Historie vollständig wiederhergestellt')};
el('historyClear').onclick=async()=>{if(!confirm('Wirklich ALLE lokalen Messwerte dauerhaft löschen? Vorher Backup erstellen!'))return;const response=await fetch('/api/v1/history/clear',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'confirm=DELETE'});status(response.ok?'Historie vollständig gelöscht':'Historie konnte nicht gelöscht werden')};
async function loadEvents(){const response=await fetch('/api/v1/events'),data=await response.json();el('events').textContent=data.events.map(item=>`${item.ts>1700000000?new Date(item.ts*1000).toLocaleString('de-DE'):'Uptime '+item.uptime_s+'s'} [${item.level}] ${item.code}: ${item.message}`).join('\n')||'Keine Ereignisse'}
el('eventsReload').onclick=loadEvents;el('eventsClear').onclick=async()=>{if(confirm('Protokoll wirklich löschen?')){await fetch('/api/v1/events/clear',{method:'POST'});loadEvents()}};
el('safeShutdown').onclick=async()=>{if(!confirm('Tracker wirklich sicher herunterfahren? Zum Starten ist danach Strom Aus/Ein oder Reset nötig.'))return;status('Minutenpuffer wird gespeichert …');const response=await fetch('/system/shutdown',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'confirm=SHUTDOWN'});status(response.ok?'Tracker wurde sicher heruntergefahren. Zum Starten Strom Aus/Ein oder Reset.':'Herunterfahren fehlgeschlagen; Tracker bleibt aktiv.')};
loadUpdate();loadEvents();
})();
